import { IProduct } from "./iproduct.interface";

export const PRODUCTS : IProduct[] = [
{
    id:  1,
    name: 'Catch The Mouse Feather Cat Toy',
    price: 15,
    description:  "PROMOTE PLAY INTRICATE & RESPONSIBILITY Catch the MouseFeather is designed to promote your cat's natural play instinct and sharpen its responsiveness. The ideal toy to keep your cat active and healthy!",
    imageUrl:  'catch_mouse.jpg',
    category: 'Cat Toys',
    rating: 4.5,
    brand:  'Kerbl Pet',
    quantity: 1 ,
    availability: true,
},
{
    id:  2,
    name:  'Cat Toy Christmas tree with bells',
    price: 13 ,
    description: "Soft toy: the outside is made of soft  material and the inside is filled with PP cotton and catnip, which feels good; healthy and harmless to the cat's body; durable and not easy to be damaged by sharp claws and teeth, it is an ideal toy to Christmas for cats.",
    imageUrl: 'tree_bell.jpg',
    category:  'Cat Toys',
    rating:  4.8,
    brand: 'FANTESI',
    quantity: 1,
    availability: true,
},
{
    id:  3,
    name:  'Molain Cat Toy Balls with Feather',
    price: 12 ,
    description: "PACKAGE INCLUDES 8 colorful large cat toy balls with feathers that multiple cats play at the same time. They won't make you feel loud.",
    imageUrl: 'foam-balls.jpg',
    category:  'Cat Toys',
    rating:  4.8,
    brand: 'Molain',
    quantity: 1,
    availability: true,
},
{
    id:  4,
    name:  'Nobby Plush Mouse',
    price: 18 ,
    description: "A cat's hunting instinct requires playful variety: Several senses of your discerning house cat are appealed to by the plush mouse. The Catnip used is tailored to the sensitive sense of smell. Thanks to the pronounced curiosity and fine sense of touch of your cat will be fascinated by this toy.",
    imageUrl: 'plush_mouse_gray.jpg',
    category:  'Cat Toys',
    rating:  4.8,
    brand: 'Nobby',
    quantity: 1,
    availability: true,
},
{
    id:  5,
    name:  'Cat fishing rod',
    price: 25 ,
    description: "Handmade interactive toy: The refills are also carefully handmade with feathers. This ensures a safe and appealing play environment for the beloved kittens. Cat fishing rod toy for kittens, stable, 107 cm.",
    imageUrl: 'cat_fishing.jpg',
    category:  'Cat Toys',
    rating:  5,
    brand: 'ROSAUI',
    quantity: 1,
    availability: false,
},{
    id: 6,
    name:  'Plush Mouse with Voice',
    price: 10,
    description: 'Exciting toys for your cat: This plush mouse with catnip is equipped with a natural mouse sound (sound chip). It measures about 8 cm without the tail, and approximately 15 cm in total.',
    imageUrl: 'plush_mouse.jpg',
    category:  'Cat Toys',
    rating: 4.7,
    brand: 'Nobby',
    quantity:  1,
    availability: true,
},
]